### ISSUE TITLE
링크

### ISSUE THREAD

**Issue by 98hyun** [sejongresearch/KISTI-Sejong-WinterSchool#1]
[병원 개/폐업](https://www.youtube.com/watch?v=7YqD0RtsmQw)

[아파트 경매 가격 예측](https://www.youtube.com/watch?v=cVde43HB8qc&feature=youtu.be)

링크가 틀려서요.  

다른분들 헷갈리지 않게  

링크 다시 해주시면 감사하겠습니다.

**Comment by unizard** [comment]
감사합니다. 처리되었습니다.
